var mongoose = require('mongoose');
exports.windowSchema = mongoose.Schema({ //Data schema with all possible data types
    inventory: String,
    manufacturer: String,
    name: String,
    variation: String,
    pageUrl: String,
    imageUrl: String,
    interiorColor: String,
    frameWidth: String,
    frameDepth: String,
    frameHeight: String,
    roughOpeningDimensions: String,
    glazingType: String,
    UFactor: Number,
    VisibleLightVTRating: Number,
    solarHeatGainCoefficient: Number,
    energyStarQualified: String,
    nailFinOrPocket: String,
    handleType: String,
    sashMaterial: String,
    screenMaterial: String,
    screenColor: String,
    productWarranty: String,
    glassWarranty: String,
    weightLBS: Number,
    specialFeatures: String,
    exteriorColor: String,
    airFiltrationRating: Number,
    swingDirection: String,
    hardwareType: String,
    jambThickness: String,
    hardwareFinish: String,
    gridPattern: String
});